Comment on exit code

diff --git a/.github/workflows/regression.yml b/.github/workflows/regression.yml
--- a/.github/workflows/regression.yml
+++ b/.github/workflows/regression.yml
@@ -16,7 +16,7 @@ jobs:
     - name: Check if regression tests should run
       run: |
         if [[ "${{ github.ref }}" != "refs/heads/main" ]] && [[ "${{ contains(env.LABELS, 'regression-required') }}" != "true" ]]; then
-          exit 78
+          exit 78  # Magic exit code to skip the job
         fi
     - name: Checkout code
       uses: actions/checkout@v4
